---
version: '2'
services:
  java:
    image: openjdk-8u111-jre-alpine
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - "5672:5672"
     - "15672:15672"