server:
  port: 8000

spring:
  rabbitmq:
    host: 192.168.178.185
    port: 5672
    username: bobsoppe
    password: bobsoppe

logging:
  level:
    ROOT:  WARN
        
tutorial:
   client:
    duration: 60000    




    
 